#!/data/data/com.termux/files/usr/bin/bash
#!/system/bin/env INIT=true
while getopts h:v:i:s: flag
do
case "${flag}" in
h) echo "Usage: mkphp -s <project name> | -v -h -i";;
v) echo "Copyright Abdulhadi5692HDI, MKPHP version: 1.0.0-2";; 
i) echo "Args after -i option is : " ${OPTARG};;
s) sh bin/app.sh ${OPTARG};;
esac
done
# bin/app.sh is the actual app
