@echo off
:: MKPHP Port for Windows
echo Making a plain PHP Project vanilla mode.
timeout 2 > nul
mkdir %1%
cd %1%
echo @echo off > mkphp_info.cmd
echo :: Project Info >> mkphp_info.cmd
echo echo Project Name: %1% >> mkphp_info.cmd
echo echo Press any key to exit. . . >> mkphp_info.cmd
echo pause >> mkphp_info.cmd
echo exit >> mkphp_info.cmd
echo // ?php > main.php
echo // Generated by mkphp >> main.php
cd ..
echo Done!
echo Press any key to exit. . .
pause>nul